---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: crossplane-provider
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./infrastructure/base/crossplane/provider
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  dependsOn:
    - name: crossplane
  targetNamespace: crossplane-system
  healthChecks:
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: providerconfigs.aws.crossplane.io
  timeout: 5m
  patches:
    - patch: |
        - op: replace
          path: /metadata/annotations/eks.amazonaws.com~1role-arn
          value: arn:aws:iam::845861764576:role/crossplane-provider-aws
      target:
        group: pkg.crossplane.io
        version: v1alpha1
        kind: ControllerConfig
        namespace: crossplane-system