apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ./secrets.yaml
  - ./crossplane-provider.yaml
  - ./crossplane-provider-config.yaml    
patches:
  - path: ./aws-load-balancer-controller-patch.yaml
  - path: ./aws-load-balancer-serviceaccount-patch.yaml
  - path: ./dns-patch.yaml
  - path: ./dns-sa-patch.yaml
  - patch: |
      - op: replace
        path: /spec/channel
        value: gitops-flux
    target:
      group: notification.toolkit.fluxcd.io
      version: v1beta1
      kind: Provider
  - patch: |
      - op: add
        path: /spec/serviceAccountName
        value: kustomize-controller
    target:
      kind: Kustomization
      namespace: (flux-system|kube-system|mariadb|crossplane-system)
  - patch: |
      - op: add
        path: /spec/serviceAccountName
        value: helm-controller
    target:
      kind: HelmRelease
      namespace: (flux-system|kube-system|mariadb|crossplane-system)
  - patch: |
     - op: add
       path: /spec/patches/-
       value:
        patch: |
          - op: add
            path: /spec/values/serviceAccount/annotations/eks.amazonaws.com~1role-arn
            value: arn:aws:iam::845861764576:role/gitops-cluster-dev-external-secrets-role
        target:
          kind: HelmRelease
          name: external-secrets
    target:
      group: kustomize.toolkit.fluxcd.io
      version: v1beta2
      kind: Kustomization
      name: external-secrets