apiVersion: v1
kind: ServiceAccount
metadata:
  name: sock-shop-reconciler
  namespace: sock-shop
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: sock-shop
  name: sock-shop-role
rules:
- apiGroups:
  - ""
  resources: 
  - pods
  - configmaps
  - services
  - endpoints
  - persistentvolumeclaims
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - statefulsets
  - replicasets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - list
  - watch
  - get
  - create
  - update
  - patch
  - delete
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses/status
  verbs:
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sock-shop-role-binding
  namespace: sock-shop
subjects:
- kind: ServiceAccount
  name: sock-shop-reconciler
  namespace: sock-shop
roleRef:
  kind: Role
  name: sock-shop-role
  apiGroup: rbac.authorization.k8s.io