apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kyverno
  namespace: kube-system
spec:
  releaseName: kyverno
  targetNamespace: kube-system
  chart:
    spec:
      chart: kyverno
      version: ">=2.3.1 <2.4.0"
      sourceRef:
        kind: HelmRepository
        name: kyverno
        namespace: kube-system
  interval: 1h0m0s
  install:
    remediation:
      retries: 3