---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  interval: 10m0s
  serviceAccountName: kustomize-controller
  path: ./infrastructure/overlays/development
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system