apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mariadb
resources:
  - namespace.yaml
  - prestashop-release.yaml
configMapGenerator:
  - name: prestashop-values
    files:
      - values.yaml=prestashop-values.yaml
configurations:
  - kustomizeconfig.yaml
