apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: aws-load-balancer-controller
spec:
  releaseName: aws-load-balancer-controller
  chart:
    spec:
      chart: aws-load-balancer-controller
      sourceRef:
        kind: HelmRepository
        name: eks-charts
        namespace: flux-system
      version: 1.4.0
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  values:
    serviceAccount:
      create: false
      name: aws-load-balancer-controller
