apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sock-shop
resources:
  - ../../../base/sock-shop
  - ./sealed-slack-secrets.yaml
  - ./sealed-git-token.yaml
  - ./registry.yaml
  - ./policy.yaml
  - ./image-automation.yaml
patches:
  - patch: |-
      - op: replace
        path: /spec/path
        value: ./deploy/kubernetes/overlays/development
    target:
      group: kustomize.toolkit.fluxcd.io
      version: v1beta2
      kind: Kustomization
      name: sock-shop-tenant
  - patch: |
      - op: replace
        path: /spec/channel
        value: gitops-flux
    target:
      group: notification.toolkit.fluxcd.io
      version: v1beta1
      kind: Provider
      name: slack
  - patch: |
      - op: replace
        path: /spec/url
        value: ssh://git@github.com/zxkane/microservices-demo
      - op: replace
        path: /spec/secretRef
        value: {}
      - op: replace
        path: /spec/secretRef/name
        value: flux-image-automation
    target:
      group: source.toolkit.fluxcd.io
      version: v1beta1
      kind: GitRepository
      name: sock-shop-tenant      