apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
spec:
  releaseName: external-dns
  targetNamespace: kube-system
  chart:
    spec:
      chart: external-dns
      version: '>=6.2.1 <7'
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  values:
    provider: aws
    aws:
      zoneType: public
    serviceAccount:
      create: false
      name: external-dns
    podSecurityContext:
      fsGroup: 65534
      runAsUser: 0