apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-dns
  annotations:
    # create IAM role via following docs,
    # https://docs.aws.amazon.com/eks/latest/userguide/specify-service-account-role.html
    # https://github.com/kubernetes-sigs/external-dns/blob/master/docs/tutorials/aws.md#iam-permissions
    # the role specified by kustomize
    # eks.amazonaws.com/role-arn: arn:aws:iam::123456789012:role/external-dns-role
    eks.amazonaws.com/sts-regional-endpoints: true