apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - sources
  - aws-load-balancer-controller
  - dns
  - mariadb
  - slack
  - ./secrets.yaml
  - policy
  - rbac.yaml
patches:
  - patch: |
      - op: add
        path: /spec/serviceAccountName
        value: kustomize-controller
    target:
      kind: Kustomization
      namespace: "(flux-system|kube-system|mariadb)"
  - patch: |
      - op: add
        path: /spec/serviceAccountName
        value: helm-controller
    target:
      kind: HelmRelease
      namespace: "(flux-system|kube-system|mariadb)"