apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: slack-url
  namespace: flux-system
spec:
  encryptedData:
    address: AgAMJH6HnwBdKChVo+7khKbeeZKUPZBZpYItkBMzD31anr5MuiCKzrhmQ/DW8xzmK5scHg91vmKsL9U2lQunhszhB8lnBiLY3JTms/wKPm9aEXkYE9hoRaN9xWx/qQa8p/Xu0Y8BNqLM6ZdcFAdkwnOMpNkaOri7wQB3R7Gw/RqTiLnq5xI2Y7BRlraN9CAsvYUnr0Mt/lZI+ZoPhKzIRhjXrhRyaiZcoojYXlDn08vZsmCUX7dYCMnJlfVP/COfNJnY9OIVF2qbxEytTDYjhWKEbv9EeCsG8r1esVUP49JToWIk2viEb9ELb0WNVrSbWfOGAdlwB911bGNYAyzcm5VrgmfhaapabVMSfGXF/DubacWkNBOiSRxmw9LulKpTBk9gPFtsMg0dtUvGLmJH/97g+ebkBawo7BrZDfPfGWF0cso+PieF+vVndSMn7o5Xq81HqphG3HtoT8nxBIjzAe3yIqDuItCKNdNZ4ev+yQJB/UudaHBsVpm5eeFckxLP/U/khgV7qyePTJGRd7dL/jEWAI2SlryNi73biGwSgxIAPM0RNuDRUGVkjXzEfa8Hl0p4HW5FnlbqFv8z7PBfGQ28WbdO/wozP2jjWQcUTaQTRi64PNClrC+LpDwNtZ7dkNhh4Ycc5DF+vNsc88SGXrjKUvpCcAL7nnXNhbXyYxMde78fffMziUy4fCNgxRieTCxmHaN0hRSuJ6hdCdMy2zUAkgbP5q95oWjJE5toX5U0aqPrqZz30aeV4YDsBDl7dliRHaEzuTa6Sv3xWiGxCqlRR4IeGiOn6c9Z5UHcC0TQs60=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: slack-url
      namespace: flux-system

