apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: flux-alert
  namespace: flux-system
spec:
  providerRef:
    name: slack
  eventSeverity: info
  eventSources:
    - kind: GitRepository
      name: '*'
      namespace: 'flux-system'
    - kind: Kustomization
      name: '*'
      namespace: 'flux-system'
    - kind: HelmRelease
      name: '*'
      namespace: 'flux-system'
  exclusionList:
    - "^Dependencies.*"      