apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: prestashop-db-secrets
  namespace: app-a
spec:
  encryptedData:
    db-password: AgBvj8FWy16Ye73gjG9vWnghEVNXxOnY0X0avNWIjn8m26/Ol98URXTDQ8V1zYhvcLpmXKUue1hMb3d11HfaKL2zBWZkUJYsWGeI2GeyworDJOv5bDxvWfXOUvtSSOmjrdwt+gKCRXGwRDzsgrVWzyS2mV4WgOya7a1Y1Ub7u/cSvVRPGjO7LMLK5I7DRnhE9/tY/+4dNKZUkP6BVVZKyQd4dmW9TouJ6hMwBZbuqlXKUDfCVDfllolJWCAXIJIgpWpwmP/SBRKLDt5y2ij9qQ15AepKSh7kxA3MgpTHe9jP5wY+weKAcnFEpxDh4CAVQe8vEH5ZFUuNhUXyv+PCxk5k4hUxWoNYQk2zcvlATGM2ZOdsiFeUscwWPmQfJgNQY1Uh8p2tpvJDsWDk3/Eea1wrkxj/mzjFl5PMjajk2/C1gRUKvSPRL4+wdcfCQ2y6576S0XYnTkDejnr8Jc4sUGpHPJfrhgzJAN9BX/cj3q2srvge62pVgs614Pb6Ke6GjHP/OBAnJGJ2Dv1hjUlNRmxLUBnUz11ukCi9OGkLBgbYb0Gld3KCKaSR8mqHFKRwCugM8gZkZGnkRic45N/wDjx6P4loJZdnRNDepMhtqgt3x7fhlbrfsbnpLpoGtpT4qXk6hU/mPklExeNfMuUflYaRogYQ9teRWbZjxbkmkCAtWkjHyyGdWKHvUjq8j4n0ENpOFiO8gbCsaierPLaS9Xyy4JBpn3kolTkkgAynp6pT6UheX1OF43X3zdBo21R/4W3juSrmkOTrem2NNdop/sRC
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: prestashop-db-secrets
      namespace: app-a

