apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: prestashop
  namespace: app-a
spec:
  encryptedData:
    prestashop-password: AgC9HHLTSdfOal+mfVEZZoSYvNdKrRjhf+UV4kl03Y4l2xueI3vIa1M8OF+Zf7OBLjWrLMETvnVmz8XJyLtCPZswKNXjoDstnoxbOunQz+D3LdiGylLp0ZEYlRzHbpLMkmpvUJyaKfoys+l81mLqPb8ZQwTXzUaH91DzKeiLxk7Em9TzRHH6zeNMt4HMR3m6uot1gkw+cWzEb/6BCsmhSX7/JxjF3xnGl07IX54b6gA1Z/FUpZtNiUXirh2U544QGsYWvyOLsj4O7KgdjtreFw4ASlx5Ls/MJMHrehTf/RDSNreRZXdedsAaOplKU7t5kdj48TICsIAuTLH11Klg76x9joaw1/mL04K0Y6BXAh7sv4CTA3SM7mDVFRCdFrEZxF13WxDQEHKSrzPFP/7alSdrcANiXxvAlblZfOCGw6PMFSHLqo88ixD6vvRsaHOABgVvBSLHika+KPEtCTTmqd5+8o45f3wPnDN59hzkl18/hc5NazR+cHV/kitY9+kCpmguquB5p2F25ZXCetM1OgMZV+++KTvk6Zl3JP7gKDziH0KA6+N0oQshQYEmiwJ90Gjx0pSnBnJ7/Ovqv7HTLahJR/v5Llk/QwQ96eeaM+D9am5pK8REtEQWNtypOPr6hu+wWGTWC4KatxI9eEEr1KhvDvhWoELz9ViiNVsda9rKIcIVBXSJcDTj7SfkJ40lwykCyUsnrBenvW7L/YjRxGEZo7BTsoZA3DE=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: prestashop
      namespace: app-a

