---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: prestashop-mariadb
  namespace: kube-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secretstore
    kind: ClusterSecretStore
  target:
    name: prestashop-mariadb
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
    - secretKey: mariadb-password
      remoteRef:
        key: dev/prestashop
        property: mariadb.password
    - secretKey: mariadb-replication-password
      remoteRef:
        key: dev/prestashop
        property: mariadb.replication-password
    - secretKey: mariadb-root-password
      remoteRef:
        key: dev/prestashop
        property: mariadb.root-password 