apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: slack-url
  namespace: kube-system
spec:
  encryptedData:
    address: AgBQCIg2jc4wa4DMqvaGQbtamHw9qY5l/pse920KB29iL70KB6tyMBfTYNnbwzxhwRX/A/Eazf1/ubU6h1FSsNXx5SADMxFoL5CKxF8BKxW4wraeo8TS178+1olEVnj9iUsBEpqyrPTna8XCf7LWGm8tjjj1mx9SdvjEaY49Kuhn/Zs+HPFmk60VgkmBbA4wDCgv70km3+N8Kdbr/0hoYT7+8s7b3lj+ISI9495/7fpnA19YhrHRny5jA+3/lvLjOC1SQ/xRfwOJDhAoOyL6xp1QA7wQSJ21Lw1yoEv0bIQPhCxEqz9rhLOLOa8E2PMJMbHI7C8bXItLpM/DczxItKf1g0jYpoBJgtcbXrIMOBPoZvPsGZ/MEt9MuOXVx+tjfib6cgz5a5lj27oMOiHAbvWKqNrGxDGb6sdB+cO8eBaw3st8iDs7rUFuwH4dn2IYl9gtSfgikr0AZU+eoyCwWeLt2JX3BAwhaLbbvBzlQJvkZPVSfyrot2Kb/ThGLzADgimI6rViTHkjBdVE2/deUnr6hqUCXgT/qG7NjzQri3i4nJjbX4pp1XOmfGKI4oM37VTbve58mRzgRtEOLBfj13HhMkb8hCUWjsZcfXHakCtDch23RbyzGjURXSWS53LL99xGGUoo0B0sw958Pnf/T4/lP+G/nLIvPNF0SHKhscQgWphzW3qxPyhikeeXIAT+0ODImge2vIsNf1lrIUQL0dhnLJP92mIdR2QpFK1g1W/Y6vbVy+rN+6PhV5DQbfURSh5DGApGgZl6xsfjKcpLU3dEjkjzls8tTPe4T/AGTahlP70=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: slack-url
      namespace: kube-system
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: slack-url
  namespace: flux-system
spec:
  encryptedData:
    address: AgBIAHbwj0fgpNO/cgMI8o5bLgrGBI3izWkjJUvJ7VEweXx7ZgBWA2YuJwFCR0G5SJFg7A393gHf2qOgW+k508bJC7U33xi7GkIakI2wPJjXNURXA+bkktUitNphPtnuWiL0SEWtq2kihI2qTaNpfOzIuyAtVhP6J3OhkN8I8awVuNj61nbUg0tWkhjjE2pZelTZorXXfLdnhSU7j6JdSurYdceE4J4zi4NdwUETLhfT5FiPk80aYQegJkjSMdrFktwOL/tAIE/e0IKw33rSb6javV/9lLUVKFM798LiVJgm5xgVlWCLs+wkO4jFKUI7XpyS4v4oAy6f47F4jDmUJRZobTMZIk9bCPTXV9U4GvqEKT3Rmgm6MGB6TuPmTQ5hcBralW6b69OCEgLHXA41I5Yo8UDLA47vHnG9D8Ldud2+CivXFK7+oDolGzxoJvVNTOlPC/lNEGnJ1fU17BDslEUVZVbHG32FMvsYeTSjFsTjm5GOv/+yp5evqd/G4qfbAmE2U1Q8PHr/ip/wyD7duz0bFtHH7b89tQZUDbc7qpUXfOhhmnQCPF10Zl+Us6F7+F/kvaXajNEFGCnKiXeLipc2qZO5FRiMBbQYNC/SRz1V9g+/D35BC5i3aguwYONblEY13PRTeb8ibR0ODNsDVRIYuqWEiS6zrU/NGYnmpaNJ7/QUMXRAGN4UZ5Czgx5Fb4Ka6Wrj35nNhvp3yJk/6LTgTWKTzIvFsedF95vML7jQuwPKBL4uKwDNxUSmPgB9OIPvPYZgRoOslYo7cwcFgZyxiY6GCHKvCiLFmgXQH6z/AOI=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: slack-url
      namespace: flux-system

