apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: slack-url
  namespace: kube-system
spec:
  encryptedData:
    address: AgBvQetM86EqET7ZCN8wwUmI7mAODgvCxygGDLvuaOXz3V7xLuFnumMxfN/5XF4bEpz19k4K3RAwuuitcLzCkmFHb+XPW7+okT8Wwnnn/8UyePrtYN8NIczmk8OuCa7J1rFlMdLwW07VJ+2ydm4aoDCsCxhOP4wqqEzlGCqO3N5IUlrQrkdnv/KLG1pTSUKmRmVlInR6bXqhZhnakN0EY+Lu/D2K+zNHcBJ3T2QDEXZRPmVcPDYUSQTaJxhzfYgJCHbK4+D2gTHoIhEVtUhF3SYzA0G9Qxl+MLdJaBIlwhOCtj8bb/hGJJzFdh53BIvZB3PX7ETUEvg2/6exu9cy+0RO0zTeZNZgmoLgRolK1nuAlE7ikCjyNI+Kh1Te/5EkJDABbNt1wtIQZ/U4FKN3W5T4kd9tq9eOapPhgijLh83A5EZqaSlbG6OWoBy8UqxL4S5R3xIG2RHr7bIhmMO8hZwoJ5AHibi8IyHCoWFi79V6alWuRUj1R4FVrn1IBo2nlzGPQDg40oJUQrru/1dQOXdeIlfd/tYPrw2c6z2GnEcNqQtr7y/fqTMLRdrFBdGYnsr6AG4QW0DLlALhRJe5OuApqQzNlSx+2AZzJyTEMXpPXz4TO7920vFtWBc0V7CNxSvoauJkKfnSGieEq+xY1I/o7wtNvlYR5ybujiHA6PS6i9Ehp9CB7u+us2YnLRrvKcwJURwErjAPE099HsHjP2nheSUqxEbhdq7LXzfl5ujO7lOUdndA7TuJrdGiYnuK0JaamZz8LzYAfyAOfdULuuuR56EunVmIiQlz6JzmEtish64=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: slack-url
      namespace: kube-system

