apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: slack-url
  namespace: kube-system
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: secretstore
    kind: ClusterSecretStore
  target:
    name: slack-url-new
    creationPolicy: Owner
    deletionPolicy: Delete
  dataFrom:
  - extract:
      key: dev/slackurl
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: slack-url
  namespace: flux-system
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: secretstore
    kind: ClusterSecretStore
  target:
    name: slack-url-new
    creationPolicy: Owner
    deletionPolicy: Delete
  dataFrom:
  - extract:
      key: dev/slackurl