apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: slack-url
  namespace: kube-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secretstore
    kind: ClusterSecretStore
  target:
    name: slack-url
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
    - secretKey: address
      remoteRef:
        key: dev/slackurl
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: slack-url
  namespace: flux-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secretstore
    kind: ClusterSecretStore
  target:
    name: slack-url
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
    - secretKey: address
      remoteRef:
        key: dev/slackurl