apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
spec:
  values:
    txtOwnerId: gitops-cluster-prod
    domainFilters[0]: gitops.test.kane.mx
    policy: sync