---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: prestashop
  namespace: app-a
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secretstore
    kind: ClusterSecretStore
  target:
    name: prestashop
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
    - secretKey: prestashop-password
      remoteRef:
        key: dev/prestashop
        property: password