apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: prestashop
  namespace: app-a
spec:
  encryptedData:
    prestashop-password: AgAyaJBrGmaljcwnmVV0oEBlraTqR1lvzTMTKWWStgbC6tLU4yAilIRlLUZapbXPpUMNeJCOZWD8aCGlnrIxpJ8BxOmY1xD5ZqdqtULfc7mBWojgDJqbr5KCcU9J23HWW3mUX4ZDGP64npmcf2QEtiwTnCBlNp2K56FZX4X3TV8DQPCCwtCGpCSe8EqMz84z0gSizxwY7n9/PaRmuFWA4WEcWWrlLBiIfJjOTTg7iIrJnyJS4rqHim0q7F9xme1C9vKWxBADrT0WTw2Al+/UQ946TkveDvMjb/K+YgNFAcQClZ33LXgLrjUrfDLQirMi1E0qveAi0X5IEJ0T3CF3fiVBio/yzR3eZm+oYfIXeR2D7Kay2sld8x97wedzL5xKruetqyEXGbkBlw+XnnF3g+HCAUedDSLJkWiFA0MrIZUb/rfFVi9WauPwmZ379vf8fdFPtVXAOpFNyrM42HwEnUrUcIKUhgH/12/U6cB+R8bGbJufUe++q/PmWqYpuvjbtD49t3ItNkocbVGutl9qYxrP1KG9kHrkafRQcpea50J9heMbTxM70goyYQnbQBolNGCYbCs9zQa2Fq1DCEqA0CXZriiRZ+4UYFt1sqyggH+hFzG14QP3lWwYVbqvIVvuscTxInBHtcSWyx2uMxeoyd/SZPiJ9M7Gvlk/6B3bgqxYUWYwxONPWATtAu+xFSNlee1RX839lmUcOKW6xOILbqNGrgCCGDk+3R0=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: prestashop
      namespace: app-a

