apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: prestashop-db-secrets
  namespace: app-a
spec:
  encryptedData:
    db-password: AgAKqH1G5swy0jV6zBJK8rsqimBJRqlYujjCedfu2FbTpavHeV44tY4Wd4Li1RveXggF5SYmXoycDzKUJhpJ3JfDpdUNc0luITqyHGoXpo/YTFp2GLPUOkUEFW5VLPtX88twJLHKXCdvP9MP//yV9shZZzgDSVntBIuc0d3PzntoTP7lv611p47Nrn5r2MLl5DJJxYv5VlN4tB3AZyFXSfFAJVD1n1uCVMrLtrFlGh8lnrkWHzYiBbIk7vQRzcRbWIO02H0WXPfTuEGK0EfikoC+5bz0w4b77Z9gz0dmHCYAcyFQoLYmo3Fruos6de0igqyc8n3uyuMBDu5Ts9tFBig1Uzhwh6u1Uj9qw8tCY+dnHdSCrfERYQLAD42DLn9pZSBmLM3YSmG5tZ0CZ0h8sZpdEbvdfF+VvUSQR2SMM/d6wkdUoBr2mJM2Ifotn7XT/Avmi2Egy2ZhwDB9tUG+JU0E+dUN1huy4EYIouku+Hz6WHl0WJ2VCg0fJc/BXikpGcYwfvZKnWwR36ggTJ5yMm63OzEC3mF9P+Jga5UlpTpFeKB7yNb7lSzKN/jJAbyESRCGHSNS2o3+XpZWzfaAk6RRgAHTqfKS2eOiUMcodhJbKwyGAyeTzCjYe+akjvWkR5u6nJsqHUKIfRLT3HvrARgdMQkbM/2SY32ZNRA/pT2my0A9l7xN0NRA24nX7vXa3FX8AIFR+g4Qo+OKIW24kKC2gZjYGZuXOhWLXmiC/PN8H5hPus1FZ+WDfgydSkfcnSS1jeuwz8nvVpI1euLzPDS1
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: prestashop-db-secrets
      namespace: app-a

