apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: prestashop
  namespace: app-a
spec:
  encryptedData:
    prestashop-password: AgAd6D3BRArom3u60tfOBCsZ8R0LVgQBfSCyb7SvuXoq1lkMldEAIR1rsKItnzSOPOwNq2Y8YmH70IhgMw0VyjtUhsIwzs9twEof1NCOhlJiHkrFR0Zoe7oQUyLDlTsFBNnKoahxuFUwLQZVRKQEi+H+LeWwwCdxq5+Eo34BcJ0RUW1JLIkzNl6rqRoZnlEHVzwZk2gnoqVWzMhoeXBuH1h0m0KBYuJIxnqrdwaU5eCDkuuTRzkCc1wjAHpOayzZm9I6TmmAIYNXCF4tjmpuQd36qnvVi00kpcoth2cqPQrcRWqA/ZTCMSMN71meG+vpR0hsKyDC7r9KvGCvAK7ozRsPcAIqYr8tm6FnSzxH2vB5crQeaU/ljgiJ8trDR9HWmqBBz9yFMZnA+SNi1n9oSZ5xO74s1hIQWY7f6+L2HN7WfSM5viFIyOvlkV4dJ2S+Qpk0yzRmyY4DKNZvcxpp4cOuVLQ/OEn9wSqEnN8EZYL9X8//KMUNrAzfkk5OX8jhinZc9bF32hRHiCi2elPRk11ZIf5M69appq63t2y/Ybd8RzrJXhWsImilU6POjk6GveRqqCDMqvCtKy8cqjWzIFC/Vni9K7P+baQ+bXKdPN+kDtHZ50ZWdvbAVLigrYriHm0vQBnIyFwPWjY2JYP9vGAud+hOBLkqJDvHEConAeMIRza6eJvCwE312/n+tS29TV93xdqiPTWx0KAxGpbKCFmwIB5RMUpTyNo=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: prestashop
      namespace: app-a

