apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: prestashop
  namespace: app-a
spec:
  encryptedData:
    prestashop-password: AgBMss2QH5HlAnVgGQKbp+QOkNlU/5d8fmx5tmM5o/u+RwcL9J870CKc8ghAz4qGLoUA6fFPNcbYrBRWVURO2DNTCB1S5fB6p2Br080CU1pF20fcz9w4IKRUMzSpPqDdmn/8qrgFNMNK4oRC3mZdID8gIdjcqAxcaR0d4rHfMLMbYLLJlTgSYBwtJvKlYhI9FtXGMy+7T6UTpnVwPvkpH4hX/OUP9gFT24V2mHj/SRGQ4AbyK7VMQLxAa303Nlj/pc7wasV6JD3bKqmgp7DxqFnQnY4YGqiu3zr4AU0nZQfmXDsWcrm7jc6U6yHT1J9KRnEN/6ariUtJTqD0bp0VMQmNMwP0Nih3xXcMHqL6DdIwTT7M3btv4+LR+msifr6I4yQiONe7Kvu8bjQi1Ykc6NVw7xY81SFHuvZJ5zUTPSvxYZEpiikDFozqldzzlEPjXf9C3uTKzZzyIpVVk2c/GR4qfdS2JvOvoOc1TKH7KaZDwZnoSjVXdI7tjWK0yFBY4itMtLPAk1tlpiY3+r6hoCLDScu42JWIRGp7/xhyx5kolUpjdT6GB8BOmy75D1uIx/kzvAbsa1lqUyRlusVs+VfJofUtF+fS77CSiHHyuvIuwJOsoYx3IvtPs7SnoWnhdwRXMgh6+nq0XAb2RdyLQGPO1Sal7X3goXK9wUXB5gZ1pmADmsnYutpmfPQsLG/ZVSYH98reqyym28FB91g17aQhox9/1AnMY4w=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: prestashop
      namespace: app-a