apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: prestashop
  namespace: app-a
spec:
  encryptedData:
    prestashop-password: AgCdpt9/6z1BU9BvIQQTk9k2By1N4xV1dhdtPp7SjVZkvGLGvfgbCVQfXL6qvGNAjZ0AWX7haQYR9BlaLRvQLdIgkO6a0JZDuED2+5gZbjDIyv2fH1v8/VsJDJ7IqYu1EOw4Q0QqX036abW2atbC0toCVOQ/NYHptuLpwldAbAVngSyN6qwEGWRuoK+VTq3iLTyV+cZapkNgbb+U5nFadJS06h+0wBXQIsSg4eB63Qx2wZ26H2k4VCC0iCd4TbSXyb/kS0UopYvnkQORXNI6F2z2XOaYGuKPL2N16AjTVeoeMt4aqY9RxRM75bpaqHOg9qa0QUFGdmRLeGTZMqe6kHsTdM4bl0KPos4KjwrL4EswEY9aN3R/WxXRJeGvNZ9MD3bu3XrhD9P8Jhfrk4m7crQaH2Gx91AJEe8EzqbQjYsohEOB0qSuV+YZj+s/I63hznN6UVuxgvww0bi3q7LUZimJgdwbkzXl9iyThUzYyagsrtX4RPphkqMk+UDDv1ZVbcCTEz7OEnawXV2zVqrsnZuhutNdlX4SNseGHhff1XmFKWK7mMsqt7nIGNoBXgSidEJyvVvaLDEOKsz1notzv2FT7i/zVw9i1pWtwqtmQTiMQM7bhpofN3pyjmANjhbDUzDANp5PRcjAKzOkPb06G5VVQz4dt3juY26qQ1GxCI9n2hbweITUOapmrK9WbXzMwjV5lQkfpni2yXWFcK7J4rln0WY0Wbs/tv0=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: prestashop
      namespace: app-a

