apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: prestashop
  namespace: app-a
spec:
  encryptedData:
    prestashop-password: AgAtPzF/+H4Ir9SRGz3Vp0kcH0+y+9wQERXL38qj4m7denquqYfFi1f6NV336IOdl/1CpqLlTfYQRap0vTNes5F48mfjThlgwJFW7aJzO8h+TjqQr8uRBDs9qyS5RzN2a4YTAFgTdsHZu48TRHLMIOdMEatMnY4IyWhpgnNx37TF2KcKL22PFeunpL74FeyOKP9i08hAWAhj831DsgU78OSJUONQUdN4WfZLK7guRTzGEitCLnNgqfNMC4IVzSxwZGTxUPcF3EWHhBA/bdCCKaAFTH48vJVs2NRgKfaeEHHm+Mrt03UBQ5K/g/9QYttaJYMlhakx6vpmfGFX7MErmIIgqRF3P0B7EO75+UvuuL8YF5kIRaOrVuKGI3s6FW0prVTRXd8/OUM757hpMvVIOVMpn5ImiE141USVG/STVPYPvuo9lb37g4zZtug/2CQCHce6Hy/Wc7/383Ma46RMOcnR/nbCh0KVXD1t7r4DjvlNMzIVg6Bx0wf86Oki+5dNNa+mW1rh5kDvS3d4sGj+g6D+t351gSxxSSaQ3u7+dB1zi81AURYX4rc3CbIgIrlgfQUZGx3METvzS2yH9Eq6XM1gFiXmygNUa2uegQIH/0eMiZ5FJz/esy2d1gv/RLyQiMJH8uNoM/cGjzOc5vhY1XGEIz4pPaswdgP/xpzZU7yZSC3ePL2k9zUmup9zXj76ZIcLzbOit4QgmCejunn6W09kHMD3mUwB2sQ=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: prestashop
      namespace: app-a

