apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: prestashop-db-secrets
  namespace: app-a
spec:
  encryptedData:
    db-password: AgC2VBbM6EbfX8+J2U79nyVZYUltUvxuQWa8uOEXb9OK+YoO7BQx32juV5zCL2NfXhQlJkoxyu8OS9C5IeA1i5BDqe5sEcQ+dl6Cx+fgTFOL8TBt5/MoE0xnFSll+phIUWAmX2lfb+o2y/oEkuRPoG4Rzoor6EphcQ00NpU1nLgmWnc1UbYRvjgYKZcxJ3xAC7MCssWM8yIVApKqnqk+Id0t2+BpAPyBH1xc15Gg0V+h/nnBqXlPv5AGzSWsW+x4lqZmJZU4GAECf2uDmSVMgZZFFtCF0DUVaHtObwSE2Z5Bu6hM/n1QVA0mTXeIAJPW3Zbve87aZxUTy4cN3I8dju1g5D/GZ4Hwxdx0xtzQoQdwJMoJggBCFgt1Z/kb/fFTUqoTatP22PWebxbFJXJq0BOsMQ2TunfG/X6x2gmuX8B3nU5P/7NWn3QJn9Oc68z0At+xdDcut07+0YDZOrKHEaHbRqaKnP6+VdINLUq+1WsicL4i+eTCUC5s9YKBOVcmRZ0TomZSQzI5uLOKj55gAZMQBTIOU9A+N2OoO/hzExmlHLgjw4oCVEW8Jx1x/qkN84XS6VqQfFhkwH9k8/rK+8hySiVdJYBRk8jSZMC0Fbr8gEp4RHg0LrwWRPm3pVF1Q3nmsG3lOiseiAx32PjjUTVw1GEnFhUGFblw12brg3GV7HWMVC/g3ZFTm7U61TEoDzKGUbZtbaARtCkuqJ+v3S8xVZMk62H0oNQpLS2/joO2sdqM8CIJU+2j3ZwOYp/iyw265pnfU8haAP8l+4juf/WD
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: prestashop-db-secrets
      namespace: app-a

