apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: slack-url
  namespace: flux-system
spec:
  encryptedData:
    address: AgB/wqThZ79MYfOyfjH70U03DAQnqAtwcgsasJNFa/70y94wfqNbzUWyhzvm/qbB3HwU+pPRQwPihOYA5VmmuTG+uQnnDOjW9exvADXFVq9oPv5isEyK7vIi+mKUhf2Nlm+YrsjVC3AVd7nDp0zh/LPJQMlduXpR672lgY213tASc4kz3W7Ol6DKwmK5D9cG6/Pq2I5T/J4b7LM4kHdJf6sgovFJbAqPrRelV7gwLj0LuiUwOCBBldlJFjEkthINrf+vHrqe7G/o/xXih0aqdvAubBU1+TLzsJ7EEzdwPz/KvcgRTZAegyA+NsOHoQ1vaTnFZxcDtnWfZ0UUnUpNppGNeBSLRFSGH3GHqb61tejmkjqQRbk30Sgk/2AJbBfFaB6Bbw0VbxYhfkDYTE82bttRridZOPFs2FdauwK0xQur9X0at/MwCO2dNUYf3HLWi9Q9eWui7cqv14H6afeCeEem3oAKn0C0sd9HsYNbw8P2Q3YPmXdx2A2lEBH+wP2ifKC7cWYtT5nHPLjmW4B4vkLXuK+k/4dVuK8Q+1+3PaC40k5B37vI0PrDrZGyGZBVXWDJXnRqV7X8P3RBG7WfrotA2Fa1bQm2HsS/gq6lBOQPxE5mVsuTV3ML58zvglrQclq0GteNGGVSlE8BweGypu3Q2fE7fceobR/LbBX5DGpR8ff9kywhfFk7Lg2AC2GIrTcymkol+x7n7Ff50X8ovOM63U0fG8P5OyelLGepoKVeU6o1HpO0VaelFiOXQC/z4+SCopON50NOHV/vIEGwKlDOX2jpgmY9G2ZSLob233rq4YA=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: slack-url
      namespace: flux-system

