apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: slack-url
  namespace: flux-system
spec:
  encryptedData:
    address: AgBZBJZG4xsx0sN+XgxxmvQd3CaH5QebIB+/1hxAnP90U0Ou6McEMlKvPnma/EEHXtVTwWRGeNrkZ6Br9ymftYUoUtXgAPzWxS+hUU/4zs9vVP+AmXiE+cug0ambkEf20yXggJSIw+lxRPsXUofyb3mZEVgyTe2QREK77Mb0BbJu/b+cZUdWidx1x58bPnUAtTMjUAhjTXbH1yA/CnGhb+9TFUx54SBPzvctKXcIoik/ZjcI/KV3x/dES2vKQ1HmoZEnjuzF1sigVrF2KdqIsiTiPwDggnQRu+ObdIWr640kLBthhXuvZPqb04ZCxJMuUuKBvebpNvQrgEUy+4sWP7P/6Td63pbLSlptVMTSbrrix+/7L8Byt39b2tgWZ8krwfJi4W63WVeDWBFvo3Gr9gtWFUCoP8z+FGmeQ5ntA047zMNhU3cVwgaYF+Zs6lgoaG9Cv/qlTsnu5sh5Zr4c1jfEYuAILmuJEwgXZWBJnKFO/epxBjmErXHTUD2V6UpY+hryyTX29AKtRVa7yzUAowevIKSAjaFFL62jFgtVeveaYKZVH+IYzszHxmhcYpJ8RlB9qSk3hOTIcv0yBm9wr8G/6UCYsoXXP1VGcio1Iv8PRJ2Dt6iLIPvKx9SvHtupiU2fZGTFH2grw9L7WLdCzdVnBS068HPNefKs7UE0ekZRUK5ua5Fab2c5JxOP9CEpv8cnW/3+a4l3wklERdZtXvEE1kSQaf6fLv/Vi5JtzC1k8ITYYT1WC5Xni3YZu/Igxa34nT73/3wSoUUKm/7Xd0zmoIgT24mDGzQCr8PyIJ43GTY=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: slack-url
      namespace: flux-system
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: slack-url
  namespace: kube-system
spec:
  encryptedData:
    address: AgBrHnPjM6RINw9Al+y1furQCIyuXMWVHYykI+LHarZaEbJSPyrOSV36jDn4RwDOy5RJk07ySOP550MOybbqDGSZurHIJZhaQf5JYmSf3XNMJUy/DnBXoI/CZekdjWs64nxSeFtM7IdjKuBaQvD+Ou+RS6oG5rntAKNTdsiJLKODvuhUclLtdK15Z3fop+cnW0GSn+i/3SiTouZE1nZgj5+1ZN3YajLdeKfMNJIO2lT2oKzEnXWnATHG0NdJuSN3jNzC4ZArPkMzsunYDCScDxF6yScJn6f1m6DbUhRp/IUFxB+4l+D0i+jtmZbDzcCLNmkekR62x5bojLF85eScf5pkB6Qhac5fv4FjFgvnZaVCOjqxu/oTo8V77Ck893E5vgR17IQUfoIo4oe+qJIImZmzKj3QR9dQpi9vrZi270ezzEXB5nBAxlYaltA4XbJnUIe1NH6nhyPD6ZyQgQrA9FzlQy+/4LHnZb8oxhOLtOnf5Cd9HTnvcyfcSSaEiMpn7oTfjBwaD6CErqZNopn+eTjtbmQyCvaWXB3lAJI8AOPKoPDiuuXZku3QBVOEzksj79fjpbGRS7TGz9sP8+y6oVisQWrWSJychRoDzfLO2l12GSLunsQwr/EOGd02GZJx9En2UOzNEAZeWy9zrkQDNcYYaoj0O8egFn6ddCdD7pUtqdzynIQNzE3fPW+HROsjpMWSwV6rfUd/OtIZwrom3+Vu3Yysj3UWp7etw11tveNiyo2qZcZc/3ANBC1/DR+IIW7YQ4HgdrHNFtC+QlLpD0oSJ7OgXyDXKQg+OENh6js8qBI=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: slack-url
      namespace: kube-system

