name: e2e
'on':
  workflow_dispatch: null
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
jobs:
  kubernetes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup tools
        uses: ./.github/actions/tools
      - name: Setup Flux
        uses: fluxcd/flux2/action@main
      - name: Setup Kubernetes
        uses: engineerd/setup-kind@v0.5.0
        with:
          version: v0.11.1
      - name: Install Flux in Kubernetes Kind
        run: |
          flux install --components-extra=image-reflector-controller,image-automation-controller --export > gotk-components.yaml
          sed '/gotk-sync\.yaml/d' ./clusters/cluster-dev/flux-system/kustomization.yaml > kustomization.yaml
          kubectl apply -k ./
          
          # check the availability of flux
          kubectl -n flux-system wait deployment/helm-controller --for=condition=Available=True --timeout=6m
          kubectl -n flux-system wait deployment/kustomize-controller --for=condition=Available=True --timeout=6m
          kubectl -n flux-system wait deployment/notification-controller --for=condition=Available=True --timeout=6m
          kubectl -n flux-system wait deployment/source-controller --for=condition=Available=True --timeout=6m
          
          # generate secret for mariadb
          kubectl apply -f - <<EOF > cat
          apiVersion: v1
          data:
            mariadb-password: YzNyRnFTNlhtOW5COUJmQmhSZjRjUHlaejR0SFdRS1pIRFZrVFhNY0hUN1Y2NjJaWUdMdUZaWTdDd3puWnlOQQ==
            mariadb-replication-password: eldrak1iTThoS0xaUkNKdkJjV2pGNVdLZ0J1SlBhV3Azd2M1Qzd0WXNGN1BrdkJHdExWclpOVnp0Wk5DREd0Vw==
            mariadb-root-password: cVlSdkZZeldLY2hhUWVmd0xxU2RyS2Y3R1dqaHlOdkVMS0tZckFId1VXOUhZczZkQ2h4bmgyY0J1NGNGejhWdg==
          kind: Secret
          metadata:
            name: prestashop-mariadb
            namespace: kube-system
          EOF
          
          kubectl -n kube-system create secret generic slack-url \
          --from-literal=address=https://hooks.slack.com/services/T0197QSA3DK/B03F6S60A1E/webhook
      - name: Setup cluster reconciliation
        run: |
          kubectl apply -f - <<EOF > cat
          apiVersion: source.toolkit.fluxcd.io/v1beta2
          kind: GitRepository
          metadata:
            name: flux-system
            namespace: flux-system
          spec:
            interval: 15m
            ref:
              branch: ${GITHUB_REF#refs/heads/}
            url: ${{ github.event.repository.html_url }}
            ignore: |
              /clusters/cluster-dev/flux-system/
              /clusters/cluster-staging/flux-system/
              /clusters/cluster-prod/flux-system/
          EOF
          flux create kustomization flux-system \
          --source=flux-system \
          --service-account=kustomize-controller \
          --path=./clusters/cluster-dev
          sleep 20
      - name: Verify cluster reconciliation
        run: >
          kubectl -n flux-system wait kustomization/infrastructure
          --for=condition=ready --timeout=3m
          
          kubectl -n kube-system wait alerts.notification.toolkit.fluxcd.io/flux-alert 
          --for=condition=Ready=True --timeout 30s
          
          kubectl -n kube-system wait alerts.notification.toolkit.fluxcd.io/kube-system-alert
          --for=condition=Ready=True --timeout 30s
      - name: Verify infra's helm reconciliation
        run: >
          kubectl -n kube-system wait helmrelease/prestashop-mariadb
          --for=condition=ready --timeout=3m

          kubectl -n kube-system wait helmrelease/external-dns
          --for=condition=ready --timeout=3m
          
          kubectl -n kube-system wait helmrelease/sealed-secrets
          --for=condition=ready --timeout=3m
      - name: Verify apps reconciliation
        run: >
          kubectl -n flux-system wait kustomization/apps
          --for=condition=ready --timeout=3m
      - name: Verify tenant 'app-a' reconciliation
        run: >
          kubectl -n app-a wait policies.kyverno.io/restrict-secrets-by-type
          --for=jsonpath='{.status.ready}'=true --timeout=1m
          
          kubectl -n app-a wait kustomization/app-a-tenant
          --for=condition=ready --timeout=3m
      - name: Verify tenant 'sock-shop' reconciliation
        run: >
          kubectl -n sock-shop wait kustomization/sock-shop-tenant 
          --for=condition=ready --timeout=1m
          
          kubectl wait ns sock-shop --for=jsonpath='{.status.phase}'=Active
          --timeout=30s
          
          kubectl -n sock-shop wait deployments/carts 
          --for=condition=Available=True --timeout=1m 
      - name: Debug failure
        if: failure()
        run: |
          kubectl -n flux-system get all
          kubectl -n flux-system logs deploy/source-controller
          kubectl -n flux-system logs deploy/kustomize-controller
          kubectl -n flux-system logs deploy/helm-controller
          flux get all --all-namespaces
          kubectl -n kube-system get all
          kubectl -n app-a get all
          kubectl -n sock-shop get all