name: e2e
'on':
  workflow_dispatch: null
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
jobs:
  kubernetes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup tools
        uses: ./.github/actions/tools
      - name: Setup Flux
        uses: fluxcd/flux2/action@main
      - name: Setup Kubernetes
        uses: engineerd/setup-kind@v0.5.0
        with:
          version: v0.11.1
      - name: Install Flux in Kubernetes Kind
        run: flux install
      - name: Setup cluster reconciliation
        run: |
          kubectl apply -f - <<EOF > cat
          apiVersion: source.toolkit.fluxcd.io/v1beta2
          kind: GitRepository
          metadata:
            name: flux-system
            namespace: flux-system
          spec:
            interval: 15m
            ref:
              branch: ${GITHUB_REF#refs/heads/}
            url: ${{ github.event.repository.html_url }}
            ignore: |
              /clusters/cluster-dev/flux-system/
              /clusters/cluster-staging/flux-system/
              /clusters/cluster-prod/flux-system/
          EOF
          flux create kustomization flux-system \
          --source=flux-system \
          --path=./clusters/cluster-dev
          sleep 20
      - name: Verify cluster reconciliation
        run: >
          kubectl -n flux-system wait kustomization/infrastructure
          --for=condition=ready --timeout=5m
      - name: Verify helm reconciliation
        run: >
          kubectl -n flux-system wait helmrelease/sealed-secrets
          --for=condition=ready --timeout=5m

          kubectl -n kube-system wait helmrelease/external-dns
          --for=condition=ready --timeout=5m
      - name: Debug failure
        if: failure()
        run: |
          kubectl -n flux-system get all
          kubectl -n flux-system logs deploy/source-controller
          kubectl -n flux-system logs deploy/kustomize-controller
          kubectl -n flux-system logs deploy/helm-controller
          flux get all --all-namespaces
